### ISSUE TITLE
how to manage time

### ISSUE THREAD

**Issue by IzzNuke** [teunjojo/SimpleAutoRestart#10]
I'm confused on that part
restart time:
- '00:00'

The time format is PM or AM because I tried to restart at 00:60 AM but nothing happened.
Can you explain to me how to set the time? Thank You.

**Comment by Fontom71** [comment]
> I'm confused on that part restart time:
> 
> * '00:00'
> 
> The time format is PM or AM because I tried to restart at 00:60 AM but nothing happened. Can you explain to me how to set the time? Thank You.

"The hour and minute when the server should restart (24 hour format)" in config.yml
