### ISSUE TITLE
[Feature Request] Ability to add multiple times for restart.

### ISSUE THREAD

**Issue by FordCorn** [teunjojo/SimpleAutoRestart#2]
It would be nice to add multiple times into the config to have server restarts, for example:

restartTime: 0:00
restartTime: 12:00

Having the config set like this would allow the server to restart at 12AM and 12PM respectively.

**Comment by teunjojo** [comment]
Added functionality in [Release v2.2.0](https://github.com/teunjojo/SimpleAutoRestart/releases/tag/v2.2.0)
