### ISSUE TITLE
[Bug] SimpleAutoRestart Does Not Enable or Set Correct Time

### ISSUE THREAD

**Issue by FordCorn** [teunjojo/SimpleAutoRestart#3]
When v2.2.0 was released there was a bit of an issue where whenever I would set the time for restarts I would have the config set like this:

```
restartTime:
- 00:00
- 12:00
```

However, when restarting the server it would change itself to this

```
restartTime:
- 00:00
- 720
```

I would get this error aswell inside on my console for the server.

> [22:11:44 INFO]: [SimpleAutoRestart] Enabling SimpleAutoRestart v2.2.0
> [22:11:44 INFO]: [SimpleAutoRestart] Reboot set for: 00:00
> [22:11:44 ERROR]: Error occurred while enabling SimpleAutoRestart v2.2.0 (Is it up to date?)
> java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
>         at com.teunjojo.SimpleAutoRestart.onEnable(SimpleAutoRestart.java:45) ~[SimpleAutoRestart-2.2.0.jar:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
>         at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-280]
>         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-280]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-280]
>         at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-280]
>         at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-280]
>         at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-280]
>         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-280]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-280]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-280]
>         at java.lang.Thread.run(Thread.java:833) ~[?:?]
> [22:11:44 INFO]: [SimpleAutoRestart] Disabling SimpleAutoRestart v2.2.0

Extra context, I am running a server on 1.20.2 using the latest version of PaperMC Build #280

**Comment by FordCorn** [comment]
After further testing (playing the server with the plugin enabled) it seems to be working with the config set and despite the console saying the plugin was disabled. I would say it's probably still worth looking into, not 100% sure.

**Comment by teunjojo** [comment]
It was working before, I'll look into it

**Comment by teunjojo** [comment]
Try:
```
restartTime:
- '12:00'
- '00:00'
```

**Comment by teunjojo** [comment]
This seems to fixed it, new release will have fixed config, but changing the config manually will work as well.
